### ISSUE TITLE
why **

### ISSUE THREAD

**Issue by kallolbiswas** [greyshell/ds_algorithm#1]
https://github.com/greyshell/ds_algorithm/blob/9def8cb3b15703bcc7097d058e01e06f836781fd/private_libs/queue/queue_sll.c#L102

**Comment by kallolbiswas** [comment]
We do not need ** to get data back

**Comment by kallolbiswas** [comment]
https://github.com/greyshell/ds_algorithm/blob/9def8cb3b15703bcc7097d058e01e06f836781fd/queue/demolib_queue_sll.c#L65  Function name is a function pointer. You can directly pass it

**Comment by greyshell** [comment]
@kallolbiswas 

> We do not need ** to get data back

Let's assume, if we are storing int type data in the queue then we need to pass an integer pointer as out parameter.
But in the present implementation, an address/pointer variable is stored in the queue. Due to this ** is required.

>Function name is a function pointer. You can directly pass it

resolved.
